apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml
patches:
  - path: configmap.yaml
  - path: networkpolicy.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hubspot-proxy
        namespace: hubspot-proxy-demo
      spec:
        template:
          metadata:
            annotations:
              springmath.io/deploy-revision: HUBSPOT_PROXY_DEPLOY_REVISION
          spec:
            nodeSelector:
              kubernetes.io/arch: arm64
            containers:
              - name: broker
                image: HUBSPOT_PROXY_IMAGE
